stages:
  - build
  - deploy

variables:
  DIST_FOLDER: dist
  ZIP_FILE_NAME: FILE_NAME_EXAMPLE.zip
  FUNCTION_NAME: FUNCTION_NAME_EXAMPLE
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  AWS_DEFAULT_REGION: $${{ secrets.AWS_DEFAULT_REGION }}

build_lambda:
  stage: build
  image: node:18
  script:
    - apt update
    - apt install zip
    - npm ci
    - npm run build
    - zip -r -j $ZIP_FILE_NAME $DIST_FOLDER
  artifacts:
    paths:
      - $ZIP_FILE_NAME

deploy_lambda:
  stage: deploy
  image: registry.gitlab.com/gitlab-org/cloud-deploy/aws-base:latest
  script:
    - export AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID
    - export AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY
    - export AWS_DEFAULT_REGION=$AWS_DEFAULT_REGION
    - aws configure list
    - aws lambda update-function-code --function-name $FUNCTION_NAME --zip-file fileb://$ZIP_FILE_NAME